feat: Add Deploy Command and Update Configurations for Compatibility
genlayerlabs/genlayer-cli pull request #153
Opened 2024-12-10 16:14 UTC by epsjunior

## Overview

This PR introduces a new `genlayer deploy` command to the CLI, enabling users to deploy smart contracts to the blockchain with ease. Several related changes were made to ensure compatibility with dependencies and the latest versions of tools.

---

## Features Added

### `genlayer deploy` Command

The new command allows users to deploy intelligent contracts

#### Options:

- `--contract <contractPath>`: Path to the intelligent contract file to deploy.
- `--args <args...>`: Positional arguments for the contract (space-separated values).

#### Usage Examples:

1. **Deploy a contract:**
   ```bash
   genlayer deploy --contract ./path/to/contract
   ```

2. **Deploy with positional arguments:**
   ```bash
   genlayer deploy --contract ./path/to/contract --args 1 2 3
   ```

## Configuration Changes

### 1. Switch to Bundler for `tsconfig.json`
- Updated `module` and `moduleResolution` to `bundler` for compatibility with the `genlayer-js` library.

### 2. `esbuild` Configuration
- Updated to use `es2020` to support `viem` library requirements.

### 3. Hardhat Service Integration
- Configured Hardhat service to fetch from Docker registry.
- Updated all environment variables to ensure compatibility with the latest version of Studio.

---

## Testing

### End-to-End Tests
- Tested the `genlayer deploy` command with the latest version of Studio using both `Ollama` and `OpenAI` validators.
- Verified contract deployment and interaction using the both front end and terminal to confirm retro compatibility.

### Deployment Command Tests
- Successfully tested deploying the `user_storage.gpy`

2024-12-10 17:01 UTC, cristiam86 requested changes

2024-12-10 17:01 UTC, cristiam86 commented on src/commands/general/deploy.ts
> +import fs from "fs";
@epsjunior this should be located in /commands/contracts/deploy.ts

2024-12-10 17:01 UTC, cristiam86 commented on src/commands/general/deploy.ts
> +    if (argsUsed && kwargsUsed) {
@epsjunior both can be used. For example:
`my_method(1, 2, 3, key1="value1", key2="value2")`

2024-12-10 17:01 UTC, cristiam86 commented on src/commands/general/deploy.ts
> +  contract?: string;
@epsjunior is this optional? on line 57 it fails if it is not specified: https://github.com/yeagerai/genlayer-cli/pull/153/files#diff-62d5003fd97556bce0bd39acb6e8bc16effc72f408a6c7574a6fb0c751173e0eR57

2024-12-10 17:01 UTC, cristiam86 commented on src/commands/general/index.ts
> +  program
@epsjunior move this to /commands/contracts

2024-12-10 17:01 UTC, cristiam86 commented on src/lib/utils/getPrivateKey.ts
> +export function getPrivateKey(): string {
@epsjunior can we try as much as possible not to have "utils" in this case it can be /lib/accounts/getPrivateKey

2024-12-10 18:52 UTC, epsjunior commented on src/lib/utils/getPrivateKey.ts
> +export function getPrivateKey(): string {
fixed on https://github.com/yeagerai/genlayer-cli/pull/153/commits/66e7ec36c55eda9a3d2b5f4cdb2d0158e28ee9ec

2024-12-10 19:05 UTC, epsjunior commented on src/commands/general/deploy.ts
> +  contract?: string;
yes, I considered using requiredOption for --contract, so Commander would throw an error if the user doesn’t provide this option. However, I plan to add a feature that allows running a script to deploy contracts, making the --contract option optional. The if statement is a temporary solution

2024-12-10 19:35 UTC, epsjunior commented on src/commands/general/deploy.ts
> +import fs from "fs";
I initially thought that all commands without subcommands would go into this folder, but you’re right, it’s better to organize them into a separate "contracts" folder :)

2024-12-10 19:51 UTC, epsjunior commented on src/commands/general/deploy.ts
> +import fs from "fs";
fixed on https://github.com/yeagerai/genlayer-cli/pull/153/commits/e548ced633272150476bb18d20549fc2a04214b1

2024-12-10 19:51 UTC, epsjunior commented on src/commands/general/index.ts
> +  program
fixed on https://github.com/yeagerai/genlayer-cli/pull/153/commits/e548ced633272150476bb18d20549fc2a04214b1

2024-12-13 13:45 UTC, mpaya5 approved these changes

2024-12-13 13:47 UTC, merged